language: python
python:
  - 2.7
  - 3.4 

before_script:
  - psql -c "CREATE USER tester WITH PASSWORD '123456';" -U postgres
  - psql -c 'create database pwman;' -U postgres
  - psql -c 'grant ALL ON DATABASE pwman to tester' -U postgres


before_install:
  - sudo apt-get update -qq
  - sudo apt-get install python-psycopg2 python3-psycopg2

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
  - "pip install -r requirements.txt"
  - "pip install coveralls"
  - "pip install ."
# command to run tests, e.g. python setup.py test
script:  
  coverage run --source=pwman setup.py test
    
after_success:
  coveralls
