language: python
python:
  - "2.7"
  
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
     - "pip install -r requirements.txt"
     - "pip install coveralls"
# command to run tests, e.g. python setup.py test
script:  
    # coverage run --source=pwman setup.py test
    # coverage run --omit=pwman/tests/*.py --source=pwman setup.py test
    coverage run --omit="pwman/tests/*.py,pwman/ui/mac.py,pwman/ui/win.py,pwman/data/convertdb.py,pwman/data/nodes_multiple_approach.py,pwman/data/models.py" --source=pwman setup.py test


after_success:
      coveralls
